### ISSUE TITLE
IDEA prosjektfiler er med i repo

### ISSUE THREAD

**Issue by pcmoen** [sondrewe/myFriends#2]
Hei,

Prosjektfilene til IDEA filene er sjekket inn. Dette gjør det litt klønete å jobbe med prosjektet, siden man får endringer på disse filene uten å egentlig gjøre noe.

Kan man fjerne katalogen fra repo'et? Eller er det en spesiell grunn for dette å sjekke inn prosjektfilene til IDEA?

Jeg gjorde en kjapp test på min maskin og fjernet .idea katalogen. IDEA håndterte pom.xml filen og prosjektet uten problemer. Checkstyle konfigurasjonen forsvinner, men det kan man kanskje løse vha Maven eller en DI tjener?

Per Christian

**Comment by pcmoen** [comment]
Vedlagt er tre skjermdumper som viser hvordan IDEA håndterer dette Maven prosjektet, siden  .idea/modules.xml er sjekket inn. Når jeg legger pom.xml filen tuller IDEA det litt til og legger til et unødvendig entry i modules.xml filen.

En reset på modules.xml filen etter importering vil få prosjektet tilbake til sjekket inn versjon og IDEA og git vil være fornøyde. Siden .idea er i .gitignore filen vil det ikke være flere ting som dukker opp etterpå, men tenkte det var litt unødvendig å måtte gå igjennom dette for nye utviklere.

<img width="518" alt="skjermbilde 2016-02-16 kl 23 29 23" src="https://cloud.githubusercontent.com/assets/5680727/13093397/54e49bb4-d505-11e5-99f3-72aade59552d.png">

<img width="270" alt="skjermbilde 2016-02-16 kl 23 28 50" src="https://cloud.githubusercontent.com/assets/5680727/13093403/637ff876-d505-11e5-92ea-aadc562cce86.png">

<img width="1029" alt="skjermbilde 2016-02-16 kl 23 30 25" src="https://cloud.githubusercontent.com/assets/5680727/13093409/6b23a51e-d505-11e5-84d7-b004aebb3abb.png">

**Comment by sondrewe** [comment]
.idea skal ikke ligge i git, men har kommet med ved en feiltakelse. Har vært litt hastverksarbeide ;-) Fjernet mappen nå.
https://github.com/sondrewe/myfriends-server/commit/0829296bd9ae23a0d4b9226eb2ac574692e24afc
